# Generated by Django 4.2.4 on 2023-09-08 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailsender', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='name',
            field=models.CharField(default='MyMailing', max_length=50, verbose_name='название'),
        ),
    ]
