# Generated by Django 4.2.4 on 2023-09-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailsender', '0003_alter_mailinglogs_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.CharField(max_length=100, unique=True, verbose_name='электронный адрес'),
        ),
    ]
