# Generated by Django 4.2.4 on 2023-09-18 12:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mailsender', '0005_client_owner_alter_mailing_frequency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailing',
            name='sending_time',
        ),
        migrations.AddField(
            model_name='mailing',
            name='body',
            field=models.TextField(blank=True, null=True, verbose_name='тело письма'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Статус активности'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время запуска рассылки'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='stop_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время завершения рассылки'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='title',
            field=models.CharField(default='Message Title>', max_length=50, verbose_name='тема письма'),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
