# Generated by Django 4.2.4 on 2023-09-21 06:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mailsender', '0007_mailing_owner_alter_mailing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='next_start',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='дата запуска рассылки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Время запуска рассылки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='stop_time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Время завершения рассылки'),
        ),
    ]
