# Generated by Django 4.2.4 on 2023-09-21 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailsender', '0008_mailing_next_start_alter_mailing_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='frequency',
            field=models.CharField(choices=[('daily', 'ежедневно'), ('weekly', 'еженедельно'), ('monthly', 'ежемесячно')], default='ежемесячно', max_length=15, verbose_name='периодичность'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='status',
            field=models.CharField(choices=[('created', 'создана'), ('running', 'запущена'), ('completed', 'завершена')], default='создана', max_length=15, verbose_name='статус рассылки'),
        ),
    ]
