# Generated by Django 4.2.4 on 2023-09-21 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailsender', '0009_alter_mailing_frequency_alter_mailing_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'permissions': [('change_mailing_status', 'Can change mailing status')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
        migrations.AlterField(
            model_name='mailing',
            name='client',
            field=models.ManyToManyField(blank=True, null=True, to='mailsender.client', verbose_name='подписчики'),
        ),
    ]
