# Generated by Django 4.2.4 on 2023-09-21 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailsender', '0010_alter_mailing_options_alter_mailing_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.CharField(max_length=100, verbose_name='электронный адрес'),
        ),
    ]
