# Generated by Django 4.2.4 on 2023-09-22 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailsender', '0012_remove_mailinglogs_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='title',
            field=models.CharField(default='Message Title', max_length=50, verbose_name='тема письма'),
        ),
    ]
