# Generated by Django 4.2.4 on 2023-09-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailsender', '0013_alter_mailing_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailinglogs',
            name='last_try',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата и время последней попытки'),
        ),
        migrations.AddField(
            model_name='mailinglogs',
            name='status',
            field=models.CharField(choices=[('ok', 'Успешно'), ('failed', 'Ошибка')], default='ok', max_length=15, verbose_name='статус попытки'),
        ),
    ]
